# ReadTheDocs 配置文件
# 文档: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

# 构建环境
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# 使用 MkDocs 构建
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Python 依赖
python:
  install:
    - requirements: requirements.txt
